CREATE TABLE TBL_ADMIN(
	ADMINID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	FIRSTNAME NVARCHAR(50) NOT NULL,
	MIDDLENAME NVARCHAR(50) NULL,
	LASTNAME NVARCHAR(50) NOT NULL,
	[USERNAME] NVARCHAR(50) NOT NULL,
	[PASSWORD] NVARCHAR(50) NOT NULL,
	CREATEDDATE DATETIME NOT NULL DEFAULT GETDATE(),
	CREATEDBY NVARCHAR(50) NULL,
	UPDATEDDATE DATETIME NULL,
	UPDATEDBY NVARCHAR(50) NULL
) ON [PRIMARY]