CREATE TABLE TBL_PACKAGE(
	PACKAGEID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	PACKAGECODE NVARCHAR(50) NOT NULL,
	PACKAGENAME NVARCHAR(50) NOT NULL,
	EVENTTYPE UNIQUEIDENTIFIER NOT NULL,
	INCLUSIONS UNIQUEIDENTIFIER NOT NULL UNIQUE DEFAULT NEWID(),
	ACCOMODATION INT NULL,
	PRICE DECIMAL(10,2) NOT NULL,
	CREATEDDATE DATETIME NOT NULL DEFAULT GETDATE(),
	CREATEDBY NVARCHAR(50) NULL,
	UPDATEDDATE DATETIME NULL,
	UPDATEDBY NVARCHAR(50) NULL
	CONSTRAINT FK_TBL_PACKAGE FOREIGN KEY (EVENTTYPE) REFERENCES TBL_EVENTTYPE(EVENTTYPEID)
) ON [PRIMARY]