CREATE TABLE TBL_CATEGORY(
	CATEGORYID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	CATEGORYNAME NVARCHAR(50) NOT NULL,
	CATEGORYDESCRIPTION NVARCHAR(MAX) NULL,
	CREATEDDATE DATETIME NOT NULL DEFAULT GETDATE(),
	CREATEDBY NVARCHAR(50) NULL,
	UPDATEDDATE DATETIME NULL,
	UPDATEDBY NVARCHAR(50) NULL
) ON [PRIMARY]