CREATE TABLE TBL_EVENTTYPE(
	EVENTTYPEID UNIQUEIDENTIFIER NOT NULL PRIMARYKEY DEFAULT NEWID(),
	EVENTNAME NVARCHAR(50) NOT NULL,
	EVENTDESCRIPTION NVARCHAR(MAX) NULL,
	CREATEDDATE DATETIME NOT NULL DEFAULT GETDATE(),
	CREATEDBY NVARCHAR(50) NULL,
	UPDATEDDATE DATETIME NULL,
	UPDATEDBY NVARCHAR(50) NULL
) ON [PRIMARY]