CREATE TABLE TBL_MENU(
	MENUID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	MENUNAME NVARCHAR(50) NOT NULL,
	MENUCODE NVARCHAR(50) NOT NULL,
	MENUIMAGE NVARCHAR(250) NOT NULL,
	MENUCATEGORY UNIQUEIDENTIFIER NOT NULL,
	MENUDESCRIPTION NVARCHAR(MAX) NULL,
	PRICE DECIMAL (10,2) NOT NULL,
	CREATEDDATE DATETIME NOT NULL DEFAULT GETDATE(),
	CREATEDBY NVARCHAR(50) NULL,
	UPDATEDDATE DATETIME NULL,
	UPDATEDBY NVARCHAR(50) NULL
	CONSTRAINT FK_TBL_MENU_MENUCATEGORY FOREIGN KEY(MENUCATEGORY) REFERENCES TBL_CATEGORY(CATEGORYID)
) ON [PRIMARY]