//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casa_emelita.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CASAEMELITAEntities : DbContext
    {
        public CASAEMELITAEntities()
            : base("name=CASAEMELITAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public DbSet<TBL_CATEGORY> TBL_CATEGORY { get; set; }
        public DbSet<TBL_EVENTTYPE> TBL_EVENTTYPE { get; set; }
        public DbSet<TBL_MENU> TBL_MENU { get; set; }
        public DbSet<TBL_INCLUSION> TBL_INCLUSION { get; set; }
        public DbSet<TBL_PACKAGE> TBL_PACKAGE { get; set; }
    }
}
