//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casa_emelita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INCLUSION
    {
        public System.Guid INCLUSIONID { get; set; }
        public System.Guid PACKAGEINCLUSION { get; set; }
        public System.Guid MENUID { get; set; }
    
        public virtual TBL_MENU TBL_MENU { get; set; }
    }
}
