//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casa_emelita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ORDER
    {
        public TBL_ORDER()
        {
            this.TBL_ORDERS = new HashSet<TBL_ORDERS>();
        }
    
        public System.Guid ORDERID { get; set; }
        public System.Guid ORDERTYPEID { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string CUSTOMEREMAIL { get; set; }
        public string CUSTOMERCONTACTNUMVER { get; set; }
        public Nullable<System.Guid> PACKAGEID { get; set; }
        public string CUSTOMERADDRESS { get; set; }
        public System.DateTime EVENTDATE { get; set; }
        public System.Guid ORDERSTATUSID { get; set; }
        public System.DateTime APPOINTMENTDATE { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
        public string SLOT { get; set; }
    
        public virtual ICollection<TBL_ORDERS> TBL_ORDERS { get; set; }
        public virtual TBL_ORDER_TYPE TBL_ORDER_TYPE { get; set; }
        public virtual TBL_PACKAGE TBL_PACKAGE { get; set; }
        public virtual TBL_ORDER_STATUS TBL_ORDER_STATUS { get; set; }
    }
}
