//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casa_emelita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ORDERS
    {
        public System.Guid ORDERSID { get; set; }
        public System.Guid ORDERID { get; set; }
        public Nullable<System.Guid> PACKAGEID { get; set; }
        public Nullable<System.Guid> MENUID { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string UDATEDBY { get; set; }
        public Nullable<int> QTY { get; set; }
        public string ORDERNOTE { get; set; }
    
        public virtual TBL_MENU TBL_MENU { get; set; }
        public virtual TBL_PACKAGE TBL_PACKAGE { get; set; }
        public virtual TBL_ORDER TBL_ORDER { get; set; }
    }
}
