//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casa_emelita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SERVICESINCLUSIONS
    {
        public System.Guid SERVICESINCLUSIONSID { get; set; }
        public Nullable<System.Guid> PACKAGEID { get; set; }
        public Nullable<System.Guid> SERVICEID { get; set; }
    
        public virtual TBL_ORDER TBL_ORDER { get; set; }
        public virtual TBL_SERVICE TBL_SERVICE { get; set; }
    }
}
