//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casa_emelita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EVENTTYPE
    {
        public TBL_EVENTTYPE()
        {
            this.TBL_PACKAGE = new HashSet<TBL_PACKAGE>();
        }
    
        public System.Guid EVENTTYPEID { get; set; }
        public string EVENTNAME { get; set; }
        public string EVENTDESCRIPTION { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
    
        public virtual ICollection<TBL_PACKAGE> TBL_PACKAGE { get; set; }
    }
}
