//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casa_emelita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ORDER_TYPE
    {
        public TBL_ORDER_TYPE()
        {
            this.TBL_ORDER = new HashSet<TBL_ORDER>();
        }
    
        public System.Guid ORDERTYPEID { get; set; }
        public string ORDERNAME { get; set; }
        public string ORDERCODE { get; set; }
        public string ORDERDESCRIPTION { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string UDATEDBY { get; set; }
    
        public virtual ICollection<TBL_ORDER> TBL_ORDER { get; set; }
    }
}
