//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casa_emelita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SERVICE
    {
        public TBL_SERVICE()
        {
            this.TBL_SERVICESINCLUSIONS = new HashSet<TBL_SERVICESINCLUSIONS>();
        }
    
        public System.Guid SERVICEID { get; set; }
        public string SERVICENAME { get; set; }
        public string SERVICEDESCRIPTION { get; set; }
        public decimal SERVICEPRICE { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
    
        public virtual ICollection<TBL_SERVICESINCLUSIONS> TBL_SERVICESINCLUSIONS { get; set; }
    }
}
