//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casa_emelita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ORDER_STATUS
    {
        public TBL_ORDER_STATUS()
        {
            this.TBL_ORDER = new HashSet<TBL_ORDER>();
        }
    
        public System.Guid ORDERSTATUSID { get; set; }
        public string ORDERSTATUSNAME { get; set; }
        public string ORDERSTATUSCODE { get; set; }
        public string ORDERSTATUSDESCRIPTION { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string UDATEDBY { get; set; }
    
        public virtual ICollection<TBL_ORDER> TBL_ORDER { get; set; }
    }
}
